IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Users')
    CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID() NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	FirstName VARCHAR(256) NOT NULL,
	LastName VARCHAR(256) NOT NULL,
	PasswordHash VARCHAR(MAX) NOT NULL,
	PasswordSalt VARCHAR(MAX) NOT NULL,
	PhoneNumber VARCHAR(15) NOT NULL
)
GO