IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Tickets')
    CREATE TABLE Tickets (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID() NOT NULL,
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	TrainId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Trains(Id) NOT NULL,
	RailroadCar INT NOT NULL,
	TrainSeat INT NOT NULL,
	Price DECIMAL(5,2) NOT NULL
	)
GO