USE RailwayManagerDb
BEGIN

ALTER TABLE Trains 
ADD CONSTRAINT DF__Trains__ArrivalD__2A4B4B5E
DEFAULT GETUTCDATE() FOR ArrivalDate;

ALTER TABLE Trains 
ADD CONSTRAINT DF__Trains__Departur__29572725
DEFAULT GETUTCDATE() FOR DepartureDate;

ALTER TABLE Trains 
ADD CONSTRAINT DF__Trains__Duration__2B3F6F97
DEFAULT GETUTCDATE() FOR Duration;

END